name: Build

on:
  - push
  - pull_request
  - workflow_dispatch
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          # - macos-latest
          # - windows-latest # zarith fails to build on Windows
        ocaml-compiler:
          - "5.2"
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout tree
        uses: actions/checkout@v4
      - name: Set-up OCaml
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}
      
      - name: Cache opam root
        uses: actions/cache@v4
        with:
          path: ~/.opam
          key: opam-root-${{ runner.os }}-ocaml-${{ matrix.ocaml-compiler }}-${{ hashFiles('flake.nix') }}

      - name: Install opam packages
        run: opam install coq dune

      - name: Dune build
        run: opam exec -- dune build --display=short --print-metrics
