name: Build

on:
  - push
  - pull_request
  - workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        coq_version:
          - '8.19.2'
          - dev
        ocaml_version: ['default']
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - uses: coq-community/docker-coq-action@v1.5.0
        with:
          coq_version: ${{ matrix.coq_version }}
          ocaml_version: ${{ matrix.ocaml_version }}
